# note: this file is automatically generated (tools/gen_py_models.py)
# which parses `src/core/qtypes.h`

from dataclasses import dataclass, field
from typing import List, Any
from .models import *

@dataclass
class PeerMaxConnections(QEventBase, QClass):
    connections: int
    ip: str

@dataclass
class RawMessage(QEventBase, QClass):
    raw: bytes
    ip: str

@dataclass
class ChannelJoin(QEventBase, QClass):
    channel: Channel
    account: Account
    password: str
    from_system: bool = False

@dataclass
class ChannelPart(QEventBase, QClass):
    channel: Channel
    account: Account
    message: str = ""
    from_system: bool = False

@dataclass
class Message(QEventBase, QClass):
    id: bytes
    nick: str
    host: str
    text: str
    user: str
    raw: bytes
    tags: Dict[str,Any] = field(default_factory=dict)
    targets: List[str] = field(default_factory=list)
    account: Account = None
    channel: Channel = None
    from_system: bool = False

@dataclass
class AuthUser(QEventBase, QClass):
    username: str
    password: str
    ip: str
    from_system: bool = False
